=== WINDOWEXPRESS/DAM2021/LM/TEORIA/U.6-XML-XSD/XML-XSD/practica3_xsd.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.w3.org/2001/XMLSchema">
	<element name="catalogoLibro">
		<complexType>
			<sequence>
				<element name="libro" maxOccurs="unbounded">
					<complexType>
						<sequence>
							<element name="titulo" type="string"/>
							<element name="autor" type="string" minOccurs="1" maxOccurs="3"/>
							<element name="fecha" type="date"/>
							<element name="ISBN" type="string"/>
							<element name="editor" type="string"/>
						</sequence>
					</complexType>
				</element>
			</sequence>
		</complexType>
	</element>
</schema>

=== WINDOWEXPRESS/DAM2021/LM/TEORIA/U.6-XML-XSD/XML-XSD/practica3_xml.xml
<?xml version="1.0" encoding="UTF-8"?>
<catalogoLibro  xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation ="practica3_xsd.xsd">
	<libro>
		<titulo>dghfg</titulo>
		<autor>fgnvfn</autor>
		<autor>AAAAA</autor>
		<fecha>1998-02-10</fecha>
		<ISBN>2165848525</ISBN>
		<editor>fgjghm</editor>
	</libro>
	<libro>
		<titulo>ghjgh</titulo>
		<autor>dsrfhdfcgb</autor>
		<fecha>2003-07-26</fecha>
		<ISBN>148769468513</ISBN>
		<editor>dhbcgncfghj</editor>
	</libro>
</catalogoLibro>
