<?xml version='1.0' encoding="iso-8859-1"?>
<!DOCTYPE personas[
<!ELEMENT personas (persona)+>
	<!ELEMENT persona (nombre, apellidos, nacimiento?, direccion+, (varon|hembra))>
		<!ELEMENT nombre (#PCDATA)>
		<!ELEMENT apellidos (#PCDATA)>
		<!ELEMENT nacimiento EMPTY>
			<!ATTLIST nacimiento dia CDATA #REQUIRED>
			<!ATTLIST nacimiento mes CDATA #REQUIRED>
			<!ATTLIST nacimiento anyo CDATA #REQUIRED>
		<!ELEMENT direccion (calle, poblacion, provincia, cpostal)>
			<!ELEMENT calle (#PCDATA)>
			<!ELEMENT poblacion (#PCDATA)>
			<!ELEMENT provincia (#PCDATA)>
			<!ELEMENT cpostal (#PCDATA)>
		<!ELEMENT varon EMPTY>
		<!ELEMENT hembra EMPTY>
		
]>
<personas>
	<persona>
		<nombre>Lucia</nombre>
		<apellidos>Perez Rodriguez</apellidos>
		<nacimiento dia="12" mes="junio" anyo="2014"/>
		<direccion>
			<calle>Caoba, 2</calle>
			<poblacion>Madrid</poblacion>
			<provincia>Madrid</provincia>
			<cpostal>28005</cpostal>
		</direccion>
		<hembra/>
	</persona>
	<persona>
		<nombre>Juan</nombre>
		<apellidos>Garcia Hernandez</apellidos>
		<nacimiento dia="23" mes="noviembre" anyo="2017"/>
		<direccion>
			<calle>Arganda, 37</calle>
			<poblacion>Madrid</poblacion>
			<provincia>Madrid</provincia>
			<cpostal>28005</cpostal>
		</direccion>
		<varon/>
	</persona>
</personas>